# More details on how to configure the Travis build
# https://docs.travis-ci.com/user/customizing-the-build/

language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository

#Skipping install step to avoid having Travis run arbitrary './gradlew assemble' task
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install:
  - true

#Don't build tags
branches:
  except:
  - /^v\d/

#Build and perform release (if needed)
script:
  - ./gradlew build -s && ./gradlew ciPerformRelease

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

after_failure:
  - cat ~/.m2/repository/com/github/magneticflux/kotlin-livedata-utils/0.2.0/kotlin-livedata-utils-0.2.0.pom
  - cat ~/.m2/repository/com/github/magneticflux/kotlin-livedata-utils/0.3.0/kotlin-livedata-utils-0.3.0.pom
  - cat ~/.m2/repository/com/github/magneticflux/kotlin-livedata-utils/0.3.1/kotlin-livedata-utils-0.3.1.pom
  - cat ~/.m2/repository/com/github/magneticflux/kotlin-livedata-utils/maven-metadata-local.xml